export const Errors = Object.freeze({
  ROUTER_UNKNOWN_SUBJECT: 'DOMAIN_SNAPSHOT_ROUTER_UNKNOWN_SUBJECT',
  ROUTER_HANDLER_ERROR: 'DOMAIN_SNAPSHOT_ROUTER_HANDLER_ERROR',
  PRECONDITION_REQUIRED: 'DOMAIN_SNAPSHOT_PRECONDITION_REQUIRED',
  COMPONENT_STATE_NOT_FOUND: 'DOMAIN_SNAPSHOT_COMPONENT_STATE_NOT_FOUND',
  COMPONENT_STATE_INVALID: 'DOMAIN_SNAPSHOT_COMPONENT_STATE_INVALID',
})
